### ISSUE TITLE
Existing pid file should raise warning on startup

### ISSUE THREAD

**Issue by willfong** [Expensify/Bedrock#71] opened 2016-12-23 04:55 UTC
Bedrock version: 43234709c216b19ae7ce7ea7a5219467bf50e773

When using "service bedrock start", the script should check to see if the pid file exists, and if so, raise an error instead of silently ignoring it. (or should be handled in another way better).

This causes a bit of confusion when bedrock crashes (and didn't clean up its files).

Things are running well:
```
root@ubuntu6:~# ps aux|grep bedrock
root      5764  0.0  0.3 400332  8012 ?        Ssl  04:46   0:00 /usr/sbin/bedrock -fork -nodeName bedrock -db /var/lib/bedrock/bedrock.db -serverHost 0.0.0.0:8888 -nodeHost 0.0.0.0:8889 -priority 200 -pidfile /var/run/bedrock.pid -quorumCheckpoint 100 -readThreads 4 -plugins status,db,jobs,cache,mysql -v -cache 10001
root      5771  0.0  0.0  14224  1012 pts/0    S+   04:47   0:00 grep --color=auto bedrock
root@ubuntu6:~# bedrock -version
43234709c216b19ae7ce7ea7a5219467bf50e773
root@ubuntu6:~# cat /var/run/bedrock.pid 
5764root@ubuntu6:~# 
```

Crash the server:
```
root@ubuntu6:~# mysql -h127.0.0.1 -e "SELECT 1 AS foo, 2 AS bar;"
ERROR 2006 (HY000) at line 1: MySQL server has gone away
root@ubuntu6:~# ps aux|grep bedrock
root      5779  0.0  0.0  14224   932 pts/0    S+   04:47   0:00 grep --color=auto bedrock
```

pid file remains:
```
root@ubuntu6:~# cat /var/run/bedrock.pid 
5764root@ubuntu6:~# 
```

Start server, but it didn't really start because pid file remains:
```
root@ubuntu6:~# service bedrock start
root@ubuntu6:~# ps aux|grep bedrock
root      5805  0.0  0.0  14224  1004 pts/0    S+   04:48   0:00 grep --color=auto bedrock
root@ubuntu6:~# cat /var/run/bedrock.pid 
5764root@ubuntu6:~# 
```

Better way to start the server is to use restart, which cleans up pids:
```
root@ubuntu6:~# service bedrock restart
root@ubuntu6:~# ps aux|grep bedrock
root      5829  0.0  0.3 400332  8060 ?        Ssl  04:48   0:00 /usr/sbin/bedrock -fork -nodeName bedrock -db /var/lib/bedrock/bedrock.db -serverHost 0.0.0.0:8888 -nodeHost 0.0.0.0:8889 -priority 200 -pidfile /var/run/bedrock.pid -quorumCheckpoint 100 -readThreads 4 -plugins status,db,jobs,cache,mysql -v -cache 10001
root      5836  0.0  0.0  14224   932 pts/0    S+   04:48   0:00 grep --color=auto bedrock
root@ubuntu6:~# cat /var/run/bedrock.pid 
5829root@ubuntu6:~# 
root@ubuntu6:~# 
```

Thanks,
-will

**Comment by quinthar** [comment] 2016-12-24 00:07
To clarify, are you saying that `service bedrock start` currently does *not* start the service if there is a leftover pidfile from a previous instance?

**Comment by willfong** [comment] 2016-12-24 05:56
Yes, that is correct. Sorry for not being clear before. Thanks!

**Comment by quinthar** [comment] 2017-01-02 00:26
@righdforsa Without actually going ahead and fixing it, can you just write up a bullet list from memory on how someone *would* go about fixing this?  I don't know anything at all about how `service` works, else I'd do it myself.

**Comment by Vadius** [comment] 2017-01-04 07:48
@quinthar, `service foo bar` just runs a script from /etc/init.d with passed parameter, e.g.:
`# service bedrock start`
is equal to
`# /etc/init.d/bedrock start`

So, I guess, @willfong has a script which runs the bedrock like that:
`/usr/sbin/bedrock -fork -nodeName bedrock -db /var/lib/bedrock/bedrock.db -serverHost 0.0.0.0:8888 -nodeHost 0.0.0.0:8889 -priority 200 -pidfile /var/run/bedrock.pid -quorumCheckpoint 100 -readThreads 4 -plugins status,db,jobs,cache,mysql -v -cache 10001`

I've tried to reproduce the bug on 880cd47, but it works fine with existing pidfile.
```
$ ./bedrock -fork -db /tmp/br.db -pidfile /tmp/br.pid
$ ps -ef | grep bedrock
vadius    9903 1  0 10:31 pts/2    00:00:00 grep bedrock ./bedrock -fork -db /tmp/br.db -pidfile /tmp/br.pid
$ kill -9 9903
$ ls -1 /tmp/br.*
br.db
br.db-shm
br.db-wal
br.pid
$ ./bedrock -clean -fork -db /tmp/br.db -pidfile /tmp/br.pid
$ ps -ef | grep bedrock
vadius    11037 1  0 10:33 pts/2    00:00:00 grep bedrock ./bedrock -fork -db /tmp/br.db -pidfile /tmp/br.pid
```

**Comment by Vadius** [comment] 2017-01-04 08:07
@quinthar, I've downloaded .deb package from your site and inspected script at `/etc/init.d/bedrock`.
It uses SSD (`/sbin/start-stop-daemon`) facility to start new instance, but has CLI option '--pidfile $PIDFILE', which causes described behavior because (quote from man):
```
       -p, --pidfile pid-file
              Check whether a process has created the file pid-file. Note: using this matching option alone might cause unintended  processes  to
              be acted on, if the old process terminated without being able to remove the pid-file.
```

I think, your package builder guys should check if existing pidfile points to existing process and remove the pidfile if there is no such process before such SSD invocation.

**Comment by righdforsa** [comment] 2017-01-04 23:28
That pretty much covers it, from the approach. We need to get the init
script into the public repo (currently in the internal configs) to
effectively delegate this task.

**Comment by willfong** [comment] 2017-01-05 02:26
Hi! For clarification, I used the default init scripts from the apt repo. Thanks for looking into this!

**Comment by basiliscos** [comment] 2017-01-08 14:17
Hi,

I've looked at the issue. The actual script `/etc/init.d/bedrock` does not matters, as the service is supervised by `systemd`. It generates the system.d service at `/run/systemd/generator.late/bedrock.service`

with the content like:

```
# Automatically generated by systemd-sysv-generator

[Unit]
Documentation=man:systemd-sysv-generator(8)
SourcePath=/etc/init.d/bedrock
Description=LSB: Start the Expensify Bedrock jobs/scheduling/cache server.
After=networking.service

[Service]
Type=forking
Restart=no
TimeoutSec=5min
IgnoreSIGPIPE=no
KillMode=process
GuessMainPID=no
RemainAfterExit=yes
ExecStart=/etc/init.d/bedrock start
ExecStop=/etc/init.d/bedrock stop
```

The problem is in `Restart=no`, it cannot be tuned as it is already hard-coded in https://github.com/systemd/systemd/blob/master/src/sysv-generator/sysv-generator.c#L192

I assume, that more-or-less desired behavior can be reached with `Restart=on-failure`, systemd will always restart daemon when it crashed.

For example, if have the `/etc/systemd/system/bedrock2.service` with content like:

```
[Unit]
Documentation=man:systemd-sysv-generator(8)
Description=LSB: Start the Expensify Bedrock jobs/scheduling/cache server.
After=networking.service

[Service]
Type=forking
Restart=on-failure
GuessMainPID=no
#RemainAfterExit=yes
PIDFile=/var/run/bedrock.pid
ExecStart=/usr/sbin/bedrock -fork -nodeName bedrock -db /var/lib/bedrock/bedrock.db -serverHost 0.0.0.0:8888 -nodeHost 0.0.0.0:8889 -priority 200 -pidfile /var/run/bedrock.pid -quorumCheckpoint 100 -readThreads 4 -plugins status,db,jobs,cache,mysql -v -cache 10001

[Install]
WantedBy=default.target
```

Then we have:

```
root@ubuntu:~# ps aux | grep bedrock
root      2966  0.0  0.1  14224   964 pts/1    S+   16:58   0:00 grep --color=auto bedrock
root@ubuntu:~# service bedrock2 restart
root@ubuntu:~# ps aux | grep bedrock
root      2977  0.0  1.6 400332  8036 ?        Ssl  16:58   0:00 /usr/sbin/bedrock -fork -nodeName bedrock -db /var/lib/bedrock/bedrock.db -serverHost 0.0.0.0:8888 -nodeHost 0.0.0.0:8889 -priority 200 -pidfile /var/run/bedrock.pid -quorumCheckpoint 100 -readThreads 4 -plugins status,db,jobs,cache,mysql -v -cache 10001
root      2986  0.0  0.1  14224   928 pts/1    S+   16:58   0:00 grep --color=auto bedrock
root@ubuntu:~# kill -9 2977
root@ubuntu:~# ps aux | grep bedrock
root      2990  0.0  1.6 400332  8168 ?        Ssl  16:59   0:00 /usr/sbin/bedrock -fork -nodeName bedrock -db /var/lib/bedrock/bedrock.db -serverHost 0.0.0.0:8888 -nodeHost 0.0.0.0:8889 -priority 200 -pidfile /var/run/bedrock.pid -quorumCheckpoint 100 -readThreads 4 -plugins status,db,jobs,cache,mysql -v -cache 10001
root      2998  0.0  0.1  14224   968 pts/1    S+   16:59   0:00 grep --color=auto bedrock
root@ubuntu:~# 
root@ubuntu:~# ps aux | grep bedrock
root      2990  0.0  1.6 400332  8168 ?        Ssl  16:59   0:00 /usr/sbin/bedrock -fork -nodeName bedrock -db /var/lib/bedrock/bedrock.db -serverHost 0.0.0.0:8888 -nodeHost 0.0.0.0:8889 -priority 200 -pidfile /var/run/bedrock.pid -quorumCheckpoint 100 -readThreads 4 -plugins status,db,jobs,cache,mysql -v -cache 10001
root      3000  0.0  0.2  14224  1080 pts/1    S+   16:59   0:00 grep --color=auto bedrock
root@ubuntu:~# kill -9 2990
root@ubuntu:~# ps aux | grep bedrock
root      3004  0.0  1.5 400332  7920 ?        Ssl  16:59   0:00 /usr/sbin/bedrock -fork -nodeName bedrock -db /var/lib/bedrock/bedrock.db -serverHost 0.0.0.0:8888 -nodeHost 0.0.0.0:8889 -priority 200 -pidfile /var/run/bedrock.pid -quorumCheckpoint 100 -readThreads 4 -plugins status,db,jobs,cache,mysql -v -cache 10001
root      3012  0.0  0.2  14224  1084 pts/1    S+   16:59   0:00 grep --color=auto bedrock
```

i.e. it always started on crash.

Unfortunately, it is not possible to have the exact behaviour you asking for, i.e. "manual-start-which-behaves-as-restart-on-service-crash", refer 
https://www.freedesktop.org/software/systemd/man/systemd.service.html for "Restart=" values (search for "Table 1. Exit causes and the effect of the Restart= settings on them").

**Comment by basiliscos** [comment] 2017-01-08 15:11
Btw, actually this is not a bug, IMHO.

For example, on my gentoo-box:

```
chimerae ~ # /etc/init.d/redis start
* Starting redis ... [ ok ]
chimerae ~ # ps aux |grep redis
redis 19559 2.0 0.0 44056 4292 ? Ssl 18:03 0:00 /usr/sbin/redis-server 127.0.0.1:6379
root 19568 0.0 0.0 11852 836 pts/1 S+ 18:03 0:00 grep --colour=auto redis
chimerae ~ # kill -9 19559
chimerae ~ # /etc/init.d/redis start
* WARNING: redis has already been started
 ps aux |grep redis
root     20331  0.0  0.0  11852   852 pts/1    S+   18:12   0:00 grep --colour=auto redis
chimerae ~ # 
```

**Comment by quinthar** [comment] 2017-01-08 15:25
Ok, so to clarify I understand, what is the "correct" behavior of `service bedrock start` if a pidfile exists?  Should it:

1. Do nothing (this is what it currently does, right?)
2. Generate a warning indicating that a pidfile exists, but *not* start the server
3. Start the server, despite the pidfile

**Comment by Vadius** [comment] 2017-01-08 15:38
Correct behavior is to start the server, despite the pidfile because there is actually no running service with such pid

**Comment by basiliscos** [comment] 2017-01-08 15:50
what to do - depends on used launcher, i.e. `systemd` in case of ubuntu 16.04. AFAIK you cannot do 1.3 under `systemd` at all. With

`Restart=always`

it will always restart on crash. I.e. once started (`service bedrock start`) systemd will always re-launch it on crash. You don't need execute `service bedrock start`. You **can**  execute that command, but it will do nothing.  Meanwhile with

`Restart=no`
 
it will never start the service again on service crash.  You can sexecute `service bedrock start` (before or after crash) but it will do nothing, again. 

So, if you can see, the result of executing command is mostly independent of `pid-file existance 

With `system-v` launcher, the launch script is under control, and you can have 1, 2 or 3.

**Comment by quinthar** [comment] 2017-01-08 15:53
@basiliscos Ok, so you are saying that the correct behavior of `Restart=no` is to *not* start the server on `service bedrock start` if there is an existing pidfile.  However, currently it doesn't even give an error message.  Would you agree that it should give an error in this scenario?

**Comment by basiliscos** [comment] 2017-01-08 16:23
Well, it depends, how to interpret the `start` command.

From systemd point of view, if you invoked  `service bedrock start` the service _is started_. Then service crashes, but anyway it _was started_. , so, when you type `service bedrock start` again (with the policy never restart == `Restart=no`), systemd knows that it was started and does nothing. 

Why no error? Because the service was started. 

I've checked: the systemd does not even executes `/etc/ini.d/bedrock`  nor `/usr/sbin/bedrock`, with `Restart=no` when you type `service bedrock start` 2nd time.

I personally agree, that systemd should say something by default. openrc (gentoo) behaves the same way, i.e. 2nd "start" command always returns success; but in default (i.e. with omitted `-q`) it also emits warning

```
chimerae ~ # ps aux |grep redis
redis    27042  0.0  0.0  44056  4252 ?        Ssl  19:20   0:00 /usr/sbin/redis-server 127.0.0.1:6379
root     27051  0.0  0.0  11852   944 pts/1    S+   19:20   0:00 grep --colour=auto redis
chimerae ~ # kill -9 27042
chimerae ~ # /etc/init.d/redis -q start && echo "OK"
OK
chimerae ~ # /etc/init.d/redis start && echo "OK"
 * WARNING: redis has already been started
OK
chimerae ~ # ps aux |grep redis
root     27065  0.0  0.0  11852   832 pts/1    S+   19:21   0:00 grep --colour=auto redis
chimerae ~ # 
```

In that sense (i.e. return success) `systemd` and `openrc` behave correcly, i.e. on 2nd start invocation return "true".

**Comment by basiliscos** [comment] 2017-01-08 16:30
Actually, all that problems are solved if you'll invoke `restart` command. And that's correct. The problem might be not only in stale pid-file, but all other resouces (i.e. locks, temporally files etc.)

on `restart` all that should be cleaned, but not on `start`.

**Comment by quinthar** [comment] 2017-01-08 16:40
Hm, well I do like the idea of outputting an error in this case if possible.

@basiliscos - Is it convenient to output an error message when running `service bedrock start` with an exiting pidflie?

**Comment by Vadius** [comment] 2017-01-08 16:42
@basiliscos, I'm not agree that `service bedrock start` should not start the server if it's not actually running.
Imagine you're in production, so there should be a way to easy start service if not running. So support engineer should just type `service bedrock start` to run the service instead of guessing what to do to run it and where he should search for pidfile (and existing pidfile is not a reason to disallow starting the service if there is no such process).
Or, as option, systemd file should autorestart the service on crash, but now it's also absent.
IMHO, if bedrock intended to be used in production environment with maximum uptime, it should have ability to autorestart on crash or be just started on default command `service bedrock start` to minimize downtime.

**Comment by basiliscos** [comment] 2017-01-08 16:54
> @basiliscos - Is it convenient to output an error message when running service bedrock start with an exiting pidflie?

https://www.freedesktop.org/software/systemd/man/systemd.service.html

I cannot find any option for that in systemd unit (and the script/daemon are not executed) - so, no way to emit warning.

**Comment by basiliscos** [comment] 2017-01-08 16:59
> Imagine you're in production, so there should be a way to easy start service if not running

Use that option for systemd unit file 

`Restart=always` 

and you'll get that in automatical way, rather tnan manual.

> So support engineer should just type service bedrock start to run the service instead of guessing 

Then, he should do `service bedrock restart`.

PS. I don't like systemd too, but that's the way it behaves.

**Comment by quinthar** [comment] 2017-01-16 12:06
@righdforsa @tylerkaraszewski Do you agree with @basiliscos that the original implemented behavior is correct and as good as can be done, so we should close this issue?

**Comment by quinthar** [comment] 2017-01-18 21:41
@basiliscos Now that the init script is in the repo (https://github.com/Expensify/Bedrock/pull/94), any new ideas on how to add an error message, or is your conclusion still the same?

**Comment by righdforsa** [comment] 2017-01-19 01:40
Like @basiliscos says, this seems to be a design decision by the systemd folks. If the "service" command is creating a systemd service under the covers in 16.04, we're limited by the implementation of that init system.

I believe we can add early "prereq" commands to the systemd service when we're managing it ourselves, (which should hopefully be in the next release) which might allow us to work around this, but I'm not sure how far in the execution path the systemd scripts even go on the 2nd start, so it would be a research project.

**Comment by quinthar** [comment] 2017-01-19 13:22
So to clarify, are you ok with the current behavior and closing this issue?

**Closed** 2018-08-15 07:10 UTC
Labels: bug
